### ISSUE TITLE
Arrange access to WOS exporting

### ISSUE THREAD

**Issue by danielturek** [karthik/RRR#2]

**Comment by danielturek** [comment]
Just received:  
Dear Daniel Turek,
Thank you for your interest in Thomson Reuters - we will be in touch shortly.

**Comment by karthik** [comment]
Can you send them a follow up email since it has been almost a month?

**Comment by danielturek** [comment]
I just had a phone conversation with Anesh (?) of Thomson Reuters technical support (1-800-336-4474).  He is re-opening technical support case number TS-02290083.  He understands what we're trying to do, and (hopefully) supports our cause.  He is passing the case to his manger, which seems to imply it will get faster attention.  They will be in touch with me via email.  Hopefully updates to follow soon.

**Comment by karthik** [comment]
Excellent! Thanks for following up @danielturek 
Let's touch base next week?

**Comment by danielturek** [comment]
Sounds good.  I'm looking over the other work you've done, too -- more to follow.

**Comment by karthik** [comment]
bump

**Comment by danielturek** [comment]
Still hassling them.  The guy who needs to send me the consent form gets back next week.....

**Comment by danielturek** [comment]
This is almost amusing:

Daniel,
I need your mailing address for the agreement.
We will generate a Statement of Work for access to support your project.
Thanks,
Brian

**Comment by karthik** [comment]
Hilarious! Let's jump through these hoops anyway and see where we get.

**Comment by danielturek** [comment]
Yes, it's going to happen, it's just dragging a little.

**Comment by danielturek** [comment]
Well, maybe I'll have the XML exporting figured out by the time this actually happens...

Daniel,
I’ve put in the request.
There’s a queue so estimate this will go out early to mid next week.
Cheers,
Brian

**Comment by danielturek** [comment]
Received this just today.  I'll start looking into how to automate queries.

Dear Valued Customer,

Thomson Reuters is pleased to grant you access to the Thomson Reuters Web of Science(TM) Web Services.  Your access will become active within one business day.

Thomson Reuters Web of Science Web Services define an automated system for mining data from Web of Science databases. They follow SOAP (Simple Object Access Protocol) for transferring request and response messages.  The services include a Web Services Description Language (WSDL). Web of Knowledge Web Services conform to the JSR224: Java API for XML-based Web services 2.0 (JAX-WS) specification.

**Comment by danielturek** [comment]
I think this is going to do it for us.  Unfortunately I'm taking off right now, but I'll follow-up later.

https://gist.github.com/domoritz/2012629

**Comment by danielturek** [comment]
Status update for exporting WOS information: I've gotten the SOAP query to run(!), which feels like we're nearly there.  Unfortunately, I can't figure a useful way to get python to export the query results to either XML or json file format.

Any help or input to making this export work is very welcomed.

You can see where we're at by executing the python script `wos.py` from my recent commit.

**Comment by danielturek** [comment]
Access to WOS has been granted.

**Comment by danielturek** [comment]
Making automated queries from WOS.  

Search terms: reproducibility, replicability, repeatability
Language: English
Dates: 1/1/2000 - 12/31/2014

Output is dumped in text files data/[searchterm].json

These files will require some work to parse into R.

Complete WOS queries may be run using:
`$ make query`
(this takes a little time, since WOS permits only 2 queries / second, and limits results to 100 records / query).
