### ISSUE TITLE
Add 3 sample search query results

### ISSUE THREAD

**Issue by karthik** [karthik/RRR#3]
- [ ] Reproducibility
- [ ] Replicability
- [ ] Repeatibility

Tagging @danielturek

Once these files are in place, I'll add the parser.

**Comment by danielturek** [comment]
Interestingly, only 1,100 hits _total_ for Replicability (2000-2015, English)

**Comment by karthik** [comment]
Nice, It was sort of intuitive that it was not a widely used term.

**Comment by danielturek** [comment]
...and only 153 for Repeatability.  So, the ...500.txt in the filenames is not technically correct for Repeatability, but I kept it for consistency.

**Comment by danielturek** [comment]
For unknown reasons, WOS search for Replicability returns 1,101 results today.  I'm fairly certain I'm doing the identical search as yesterday.  The first 500 records are downloaded and pushed to repo.

**Comment by karthik** [comment]
That is weird. Trying to reach someone at Thompson Reuters.

**Comment by danielturek** [comment]
They've been in touch with me today.  Re-routing me to the correct department.  I'll let you know if/when anything interesting happens.
